"""Generate an llms.txt draft from a site's sitemap (or homepage links).

Format per https://llmstxt.org: H1 site name, blockquote summary, then
H2 sections of `- [title](url): description` links.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass

import httpx
from selectolax.parser import HTMLParser

from beacon.discover import crawlable_urls
from beacon.fetch import Site

MAX_PAGES = 20
MAX_FULL_CHARS = 10_000


@dataclass
class Page:
    url: str
    title: str
    description: str
    section: str


async def generate_llms_txt(site: Site) -> str:
    homepage = await site.homepage()
    site_title, site_description = _title_and_description(homepage)
    site_title = site_title or site.domain

    urls = await crawlable_urls(site)
    described = await asyncio.gather(*(_describe(site, url) for url in urls[:MAX_PAGES]))
    pages = [page for page in described if page is not None]

    lines = [f"# {site_title}", ""]
    if site_description:
        lines += [f"> {site_description}", ""]
    lines += [
        "<!-- Draft generated by Beacon. Review each entry: keep the pages",
        "     an agent should read first, remove the rest, and correct wording. -->",
        "",
    ]
    for section in dict.fromkeys(page.section for page in pages):
        lines.append(f"## {section}")
        lines.append("")
        for page in pages:
            if page.section == section:
                suffix = f": {page.description}" if page.description else ""
                lines.append(f"- [{page.title}]({page.url}){suffix}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


async def generate_llms_full_txt(site: Site) -> str:
    """llms-full.txt companion: the same curated pages, with full extracted text."""
    homepage = await site.homepage()
    site_title, site_description = _title_and_description(homepage)
    site_title = site_title or site.domain

    urls = await crawlable_urls(site)
    sections = await asyncio.gather(*(_full_section(site, url) for url in urls[:MAX_PAGES]))

    lines = [f"# {site_title}", ""]
    if site_description:
        lines += [f"> {site_description}", ""]
    body = "\n\n---\n\n".join(section for section in sections if section)
    if body:
        lines.append(body)
    return "\n".join(lines).rstrip() + "\n"


async def _full_section(site: Site, url: str) -> str | None:
    response = await site.get(url)
    if response is None or response.status_code >= 400:
        return None
    title, _ = _title_and_description(response)
    return f"## {title or httpx.URL(url).path}\n{url}\n\n{_page_text(response.text)}"


def _page_text(html: str) -> str:
    tree = HTMLParser(html)
    for node in tree.css("script, style, noscript, template, svg"):
        node.decompose()
    text = tree.body.text(separator=" ") if tree.body else ""
    return " ".join(text.split())[:MAX_FULL_CHARS]


def _title_and_description(response: httpx.Response | None) -> tuple[str, str]:
    if response is None or response.status_code >= 400:
        return "", ""
    tree = HTMLParser(response.text)
    title_node = tree.css_first("title")
    title = title_node.text(strip=True) if title_node else ""
    meta = tree.css_first('meta[name="description"]')
    description = (meta.attributes.get("content") or "").strip() if meta else ""
    return title, description


async def _describe(site: Site, url: str) -> Page | None:
    response = await site.get(url)
    if response is None or response.status_code >= 400:
        return None
    title, description = _title_and_description(response)
    path = httpx.URL(url).path
    first_segment = path.strip("/").split("/")[0] if path.strip("/") else ""
    section = first_segment.replace("-", " ").replace("_", " ").title() or "Main"
    return Page(url=url, title=title or path, description=description, section=section)
